spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.136/zwx-order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /zwx-order
#logging:
  #pattern:
     #console: "%d - %msg%n"
  #file:
    #name: /var/log/tomcat/zwx-order.log
  #level:
    #com.zwx: debug
