spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://116.62.108.144/zwx-order?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  port: 8080
  servlet:
    # url前缀 并且打包后项目的名字
    context-path: /sell
#logging:
  #pattern:
     #console: "%d - %msg%n"
  #file:
    #name: /var/log/tomcat/zwx-order.log
  #level:
    #com.zwx: debug
